name: shopping-basket
channels:
  - defaults
dependencies:
  - attrs=22.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - colorama=0.4.6
  - exceptiongroup=1.0.4
  - iniconfig=1.1.1
  - libffi=3.4.4
  - more-itertools=8.12.0
  - openssl=1.1.1t
  - packaging=23.0
  - pip=23.0.1
  - pluggy=1.0.0
  - pytest=7.3.1
  - python=3.10.1t
  - pyyaml=6.0
  - setuptools=66.0.0
  - sqlite=3.41.2
  - texttable=1.6.4
  - tk=8.6.12
  - tomli=2.0.1
  - tzdata=2023c
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - xz=5.4.2
  - yaml=0.2.5
  - zlib=1.2.13
